version: '3.9'

services:
  php-env:
    build: .
    volumes:
      - ./forms-profissional:/var/www/html
    ports:
      - "9000:80"
    depends_on:
      - mysql_db
    networks:
      - app-network

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9001:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: user
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
