version: '3.8'

services:
  # Apache + PHP Service using custom Dockerfile
  app:
    build: 
      context: . # Diretório atual contendo o Dockerfile e o código do aplicativo
    container_name: php_apache
    ports:
      - "8095:80"
    volumes:
      - ./forms-profissional:/var/www/html # Mapeia o código do seu aplicativo para o diretório do servidor web
    restart: always

  # Python Service
  python:
    image: python:3.9
    container_name: python_service
    volumes:
      - ./forms-profissional:/usr/src/app
    working_dir: /usr/src/app
    command: python python.py
    restart: always

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306" # Porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db

volumes:
  db_data:
